### ISSUE TITLE
ISC tutorial 2025

### ISSUE THREAD

**Issue by ocaisa** [EESSI/isc-tutorial#31]
Where do we fit? (5 max)

- [ ]  Programming Environments & System Software
  - [ ] Compiler and Tools for Parallel Programming
  - [x] HPC in the Cloud and HPC Containers
- [ ] Algorithms, Methods & Performance
  - [x] Optimizing for Energy and Performance
- [ ] Applications & Use Cases
  - No clear fit but could select a variety of the options 
- [ ] Machine Learning & AI
  - [ ] ML Systems and Tools
- [ ] Community & HPC
  - [x] Education and Training

I would choose these 3 and then 2 from Applications and Use cases

**Comment by ocaisa** [comment]
Besides the information within the online submission form, the following information needs to be uploaded within a single PDF file with the following sections:

- General Information
  - [x] Title of the tutorial
  - [ ] Tutorial author(s) information
   - [ ] bios
- [ ] Abstract (Maximum words: 500)
- A detailed description of the tutorial content (Maximum pages: 3)
  - [ ] Overview and goals of the tutorial (takeaways for the audience)
  - [ ] Targeted audience
  - [ ] Detailed outline of the tutorial (with time slots)
  - [ ] Description of hands-on activities, if applicable
  - [ ] Updates from previous presentations, if applicable
  - [ ] Number of attendees from previous tutorials, if applicable
  - [ ] URLs to sample slides and other material
- Logistics
  - [ ] Length of the tutorial: half-day (3.5 hours) or full-day (7 hours)
  - [ ] Percentage of content split as beginner/intermediate or intermediate/advanced
  - [ ] Requirements for attendees (e.g., laptop, remote server account)
  - [ ] Estimated number of attendees (with a short explanation, if applicable)
- [ ] Resume or CV of each presenter, including a list of recently taught courses or tutorials (2 pages maximum per presenter)
- [ ] Travel funding request, if applicable (see TRAVEL SUPPORT section)

- [ ] The tutorial organizers will have to align their program with the tutorial break schedule (morning sessions are from 9:00 a.m. to 11:00 a.m. and 11:30 a.m. to 1:00 p.m.; afternoon sessions are from 2:00 p.m. to 4:00 p.m. and 4:30 p.m. to 6:00 p.m., with coffee breaks and lunch in between). Catering during coffee and lunch breaks will be provided to all registered tutorial attendees.

### Review Process

A minimum of 3 reviewers will review each tutorial.

The proposal’s review criteria include originality, significance, timeliness, impact, community interest, attendance in prior years (if applicable), quality, hands-on activity, and clarity.

Reviews will include actionable feedback related to the length of the tutorials and the organization of the content (for example, suggestions to add and remove some content).

**Comment by ocaisa** [comment]
We will grant complimentary tutorial passes to a limited number of tutorial presenters:
- Full-day tutorials: at most, 6 presenters
- Half-day tutorials: at most, 3 presenters

**Comment by boegel** [comment]
> Where do we fit?
> 
>     * [ ]   Programming Environments & System Software
>       
>       * [ ]  Compiler and Tools for Parallel Programming
>       * [ ]  HPC in the Cloud and HPC Containers
> 
>     * [ ]  Algorithms, Methods & Performance
>       
>       * [ ]  Optimizing for Energy and Performance
> 
>     * [ ]  Applications & Use Cases
>       
>       * No clear fit but could select a variety of the options
> 
>     * [ ]  Machine Learning & AI
>       
>       * [ ]  ML Systems and Tools
> 
>     * [ ]  Community & HPC
>       
>       * [ ]  Education and Training

We can only pick 5 max here, so we should cherry pick a bit

**Comment by boegel** [comment]
tutorial submitted \o/
